XMC4500 Barebone Template: src/main.c File Reference
main.c File Reference
#include <debug_lib.h>
#include <stdio.h>
#include <xmc_gpio.h>
#include "test_uart.h"
#include "tio_delay.h"
Macros
#define TICKS_PER_SECOND 1000
#define TICKS_WAIT 500
#define LED1 P1_10
#define LED2 P1_11
#define LED3 P1_12
#define PinOut P1_6
#define RX_BUFFER_SIZE 64
Functions
void SysTick_Handler (void)
void activALL ()
void clearALL ()
int main (void)
Detailed Description
Date
08 Sep, 2015
Version
1.0.0
GPIO toggle example flashes the leds of the board with a periodic rate. LED1 is connected to P1.10 LED2 is connected to P1.11 LED3 is connected to P1.12
History
Version 1.0.0 Initial
Definition in file main.c.
Macro Definition Documentation
LED1
#define LED1 P1_10
Definition at line 56 of file main.c.
Referenced by activALL(), clearALL(), main(), and SysTick_Handler().
LED2
#define LED2 P1_11
Definition at line 57 of file main.c.
Referenced by activALL(), clearALL(), main(), and SysTick_Handler().
LED3
#define LED3 P1_12
Definition at line 58 of file main.c.
Referenced by activALL(), clearALL(), and main().
PinOut
#define PinOut P1_6
Definition at line 59 of file main.c.
Referenced by main().
RX_BUFFER_SIZE
#define RX_BUFFER_SIZE 64
Definition at line 61 of file main.c.
TICKS_PER_SECOND
#define TICKS_PER_SECOND 1000
Definition at line 53 of file main.c.
TICKS_WAIT
#define TICKS_WAIT 500
Definition at line 54 of file main.c.
Referenced by SysTick_Handler().
Function Documentation
activALL()
void activALL ()
Definition at line 77 of file main.c.
References _tio_busy_waiting(), LED1, LED2, and LED3.
Referenced by main().
                {
     XMC_GPIO_SetOutputHigh(LED1);
     XMC_GPIO_SetOutputHigh(LED2);
     XMC_GPIO_SetOutputHigh(LED3);
     _tio_busy_waiting(50000000);
 }
clearALL()
void clearALL ()
Definition at line 84 of file main.c.
References _tio_busy_waiting(), LED1, LED2, and LED3.
Referenced by main().
                {
     XMC_GPIO_SetOutputLow(LED1);
     XMC_GPIO_SetOutputLow(LED2);
     XMC_GPIO_SetOutputLow(LED3);
     _tio_busy_waiting(5000000);
 }
main()
int main (void)
Definition at line 91 of file main.c.
References _tio_busy_waiting(), _tio_busy_waiting_with_callback(), activALL(), clearALL(), initRetargetSwo(), LED1, LED2, LED3, and PinOut.
                {
     XMC_GPIO_CONFIG_t config;
     int i=5000000;
     int y=0;
     initRetargetSwo();
     void (*fptr)() = &activALL;
     config.mode = XMC_GPIO_MODE_OUTPUT_PUSH_PULL;
     config.output_level = XMC_GPIO_OUTPUT_LEVEL_HIGH;
     config.output_strength = XMC_GPIO_OUTPUT_STRENGTH_MEDIUM;
     XMC_GPIO_Init(LED1, &config);
     config.output_level = XMC_GPIO_OUTPUT_LEVEL_LOW;
     XMC_GPIO_Init(LED2, &config);
     XMC_GPIO_Init(LED3, &config);
     XMC_GPIO_Init(PinOut, &config);
     while(1) {
         XMC_GPIO_SetOutputHigh(LED1);
         _tio_busy_waiting(i);
         XMC_GPIO_SetOutputLow(LED1);
         XMC_GPIO_SetOutputHigh(LED2);
         _tio_busy_waiting(i);
         XMC_GPIO_SetOutputLow(LED2);
         XMC_GPIO_SetOutputHigh(PinOut);
         _tio_busy_waiting(i);
         XMC_GPIO_SetOutputLow(PinOut);
         XMC_GPIO_ToggleOutput(LED3);
         _tio_busy_waiting(i);
         XMC_GPIO_ToggleOutput(LED3);
         _tio_busy_waiting(i);
         XMC_GPIO_ToggleOutput(LED3);
         _tio_busy_waiting(i);
         XMC_GPIO_ToggleOutput(LED3);
         _tio_busy_waiting(i);
         //activALL();
         //_tio_busy_waiting(i);
         clearALL();
         _tio_busy_waiting_with_callback(i, fptr);
         clearALL(y);
     }
 }
SysTick_Handler()
void SysTick_Handler (void)
Definition at line 63 of file main.c.
References LED1, LED2, and TICKS_WAIT.
{
     static uint32_t ticks = 0;
     static int32_t cnt = 0;
     ticks++;
     if (ticks == TICKS_WAIT) {
         XMC_GPIO_ToggleOutput(LED1);
         XMC_GPIO_ToggleOutput(LED2);
         printf("Testing... %d\n", (int)cnt++);
         ticks = 0;
     }
 }