XMC4500 Barebone Template: src/tio_delay.c File Reference
tio_delay.c File Reference
#include <tio_delay.h>
Functions
unsigned int _tio_busy_waiting (unsigned int delayTime)
function is waiting for the delayTime (1 delayTime ~ 10 CPU ticks)
unsigned int _tio_busy_waiting_with_callback (unsigned int delayTime, void(*fptr)(void))
function is waiting for the delayTime (1 delayTime ~ 10 CPU ticks) afterwards a function gets executes
Function Documentation
_tio_busy_waiting()
unsigned int _tio_busy_waiting (unsigned int delayTime)
function is waiting for the delayTime (1 delayTime ~ 10 CPU ticks)
Parameters
delayTime ... how long the programm should wait
Returns
0 ... success 1 ... error: no time to wait
Definition at line 25 of file tio_delay.c.
Referenced by activALL(), clearALL(), and main().
 {
     while(delayTime--)
     {
         __NOP();
     }
     return 0;
 }
_tio_busy_waiting_with_callback()
unsigned int _tio_busy_waiting_with_callback (unsigned int delayTime, void(*)(void) fptr)
function is waiting for the delayTime (1 delayTime ~ 10 CPU ticks) afterwards a function gets executes
Parameters
delayTime ... time to wait fprt ........ function which gets executed after the delayTime is over
Returns
0 ... success 1 ... error: no time to wait
Definition at line 45 of file tio_delay.c.
Referenced by main().
 {
     while(delayTime--)
     {
         __NOP();
     }
     (*fptr)();
     return 0;
 }